name: Scala CI

on:
  push:
    branches: [ 1.6.x ]

jobs:
  image-creation:
    runs-on: ubuntu-latest
    steps:
      - name: trigger single Job
        uses: actions/checkout@v3
        with:
          url: "http://127.0.0.1:8080/"
          user: "admin"
          token: ${{ secrets.TOKEN }}
          job: "devGitPullLagomSample3"
      - run: echo "jenkins"
