name: Scala CI

on:
  pull_request:
    branches: [ 1.6.x ]
    types: [closed]

jobs:
  image-creation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: trigger single Job
        with:
          url: "http://127.0.0.1:8080/"
          job: "devGitPullLagomSample3"
      - run: echo "jenkins"
