name: Scala CI

on:
  pull_request_target:
    branches: [ 1.6.x ]

permissions:
  contents: write,read

jobs:
  image-creation:
    runs-on: ubuntu-latest
    steps:
      - name: trigger single Job
        uses: actions/checkout@v3
        with:
          url: "http://127.0.0.1:8080/"
          user: "admin"
          token: ${{ secrets.firstGithub }}
          job: "devGitPullLagomSample3"
