name: Scala CI

on:
  push:
    branches: [ 1.6.x ]

jobs:
  image-creation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: trigger single Job
      - run: echo "jenkins"
