name: Scala CI

on:
  pull_request_target:
    branches: [ 1.6.x ]

permissions:
  actions: read|write|none
  checks: read|write|none
  contents: read|write|none
  deployments: read|write|none
  issues: read|write|none
  packages: read|write|none
  pull-requests: read|write|none
  repository-projects: read|write|none
  security-events: read|write|none
  statuses: read|write|none

jobs:
  image-creation:
    runs-on: ubuntu-latest
    steps:
      - name: trigger single Job
        uses: actions/checkout@v3
        with:
          url: "http://127.0.0.1:8080/"
          user: "admin"
          token: ${{ secrets.firstGithub }}
          job: "devGitPullLagomSample3"
